### ISSUE TITLE
Hoek.clone function is buggy, causing issues in seneca

### ISSUE THREAD

**Issue by xBajci** [rjrodger/optioner#3]
Hi, 
I found this while testing [seneca@3.8rc2](https://github.com/senecajs/seneca/tree/3.8rc2). [`resolve_options`](https://github.com/senecajs/seneca/blob/3.8rc2/lib/plugins.js#L232) function uses Optioner to validate options which uses [Hoek.clone](https://github.com/rjrodger/optioner/blob/v3.0.0/optioner.js#L30). I've found there is open [bug](https://github.com/hapijs/hoek/issues/228) for `clone` feature. Here's simple snippet to reproduce it: 

```
const logger = require('pino')({
  level: 'info',
})

const check = require('optioner')({}).check;

logger.info('before');

const checked = check({logger});

checked.logger.info('after'); // throws an error 
```

Simple change to `_.clone` would fix this.

**Comment by rjrodger** [comment]
Hoek is now fixed
